### ISSUE TITLE
Choosing the Previous Homework for our Recent Work

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework4G4#1]
Hy
 Whose homework are we going to implement in our work?

**Comment by poojashresthacode** [comment]
@pratibha77118 @WildJimmy let's discuss.

**Comment by tirthbha** [comment]
@poojashresthacode Probably, we are going to choose HW2 i.e., different implementations (For Loops, NumPy Built-in Functions and , NumPy Einstein Notation Function) for matrix multiplication and dot product operations in Python for our task. What about you ?

**Comment by AhmedCode99** [comment]
good to know
