### ISSUE TITLE
Steps to follow!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G4#11]
Basically, we will do the following steps for this task, if I were not wrong:
1) Initialize GitHub Actions by creating a .yml file within .github/workflows in the repository.
2) Define Workflow Triggers by specifying events like push or pull request to the main branch that initiate the workflow, which includes check out the repository, set up a Python environment, install necessary Python packages: numpy, matplotlib, pytest, flake8, perform linting using flake8, and run unit tests with pytest.
3) Finally, the Documentation part, where we will write instructions detailing the process of creating and configuring theGitHub Actions workflow.
Correct me if I was wrong here.

**Comment by poojashresthacode** [comment]
Hey tirth, I have created a yml file for unit testing in my repo. But it is reported that all jobs have failed. Have you tried it?

**Comment by poojashresthacode** [comment]
@tirthbha

**Comment by tirthbha** [comment]
@poojashresthacode Yeah there might be problem with the code. Can you show me the error that you got there.

**Comment by poojashresthacode** [comment]
So, I created the workflow for unit testing from the code that the professor pushed in our repo. And I got an error message.
![370333279_1001713951034697_8104607040999994657_n](https://github.com/ubsuny/23-Homework4G4/assets/143756553/d8c297da-b4a3-4eec-8c03-efd5b438170d)

**Comment by tirthbha** [comment]
@poojashresthacode This the message which  informs  you that code fails to execute. The actual error is shown in the workflow file. Can you show me that error what exactly it was?

**Comment by poojashresthacode** [comment]
@tirthbha The issue was resolved. Sorry, I forgot to mention it here. Thankyou for helping.
