### ISSUE TITLE
To create directory

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G4#12]
Do we need to create the directory ".github/workflows/filename.yml" to the main repository or to own repository?

**Comment by pratibha77118** [comment]
We need to create the directory on our own repository after checking if it already exits or not?

**Comment by poojashresthacode** [comment]
it should be done in ur own repo, as I believe.

**Comment by tirthbha** [comment]
If it is true, how could we able to see the github actions for the issues created?

**Comment by poojashresthacode** [comment]
@tirthbha Did you create it on the main repo?

**Comment by tirthbha** [comment]
@poojashresthacode I did in my own repo and then sent a merge request to the main.

**Comment by poojashresthacode** [comment]
Okay.
