### ISSUE TITLE
Homework Chosen

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework4G4#14]
Hy @WildJimmy, We, me, and @pratibha77118 have decided to use homework 3 of the G1 group for our work. Is it okay for you?

**Comment by poojashresthacode** [comment]
The topic was determining the time period of simple pendulum.

**Comment by WildJimmy** [comment]
Yep that works for me! I didn't realize that had been discussed so I was just offering a suggestion earlier

**Comment by pratibha77118** [comment]
@WildJimmy We do wanna know if you are okay with this choice. We tried to reach you through issues.  It's all about about implementing the git hub action so there won't be any problem with the choice any project we did earlier.

**Comment by WildJimmy** [comment]
Yep that works for me. I thought I responded to the issues I was mentioned on so my apologies. I'm more than happy to do the documentation

**Comment by poojashresthacode** [comment]
It,s okay @WildJimmy . No worries. The deadline is tomorrow. Can you finish it till 10?

**Comment by WildJimmy** [comment]
Closing since we've finished the work here
