### ISSUE TITLE
Task Distributed

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework4G4#15]
Hi @WildJimmy,
I allocated the tasks as follows:
Algorithm: @pratibha77118 
Unit test: @poojashresthacode 
Documentation : @WildJimmy 
Please inform me if we have any problem with this allocation.

**Comment by WildJimmy** [comment]
Yep, just mentioned this on the other issue but I'm happy with doing the documentation

**Comment by pratibha77118** [comment]
I am gonna assigned the task by creating milestone once I get accepted for maintainer.

**Comment by poojashresthacode** [comment]
We don't have any problem.
