### ISSUE TITLE
Work Distribution.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework4G4#2]
Let;s decide who's going to be the maintainer.

**Comment by poojashresthacode** [comment]
@pratibha77118 @WildJimmy Who will be the maintainer/ Let's decide fast and work on our homework.

**Comment by poojashresthacode** [comment]
@pratibha77118 Do you want to be the maintainer?

**Comment by WildJimmy** [comment]
Hi All,

I have already been the maintainer twice, so I would honestly prefer it if one of you could @poojashresthacode @pratibha77118, but if that's not possible I have a good handle on how to do it.

**Comment by AhmedCode99** [comment]
ok
