### ISSUE TITLE
Open Pull Requests

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G4#33]
@pratibha77118 There's some open pull requests from the past couple of days. Could you please merge or pull them so I know which version of the code to be documenting? I will finish the documentation tomorrow morning so no worries if further changes still must be made

**Comment by pratibha77118** [comment]
@WildJimmy 
I checked the pull request and they are not the final one to be merged. 
 I think @poojashresthacode is still working on unit test.

**Comment by pratibha77118** [comment]
I have not done the pylint for the algorithm, gonna finish it by tomorrow. Could you please check on .yml file I used to run the algorithm. I am gonna use the same file for pylint too.

**Comment by poojashresthacode** [comment]
Yeah, that file was not the final one. I will send the merge request for the final files.
