### ISSUE TITLE
No Linting in the YAML Action File

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G4#34]
It looks like the YAML file doesn't lint commits to the repository. Is this correct? If so will we be adding this feature? I only ask so I can write the documentation a little bit and explain the process of linting with actions

**Comment by pratibha77118** [comment]
I do think so. How can we add this feature?  Any suggestion on this?

**Comment by poojashresthacode** [comment]
I don't understand the question. Can you please explain?

**Comment by pratibha77118** [comment]
I did the pylint for algorithm and have resolved few issues ( not all).
