### ISSUE TITLE
What should I be including in the changelog?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G4#36]
It seems like we won't have too much to change in the algorithm. Should I simply note this in the documentation, or is there more information I can include to go more in depth on why the formatting was not changed?

**Comment by poojashresthacode** [comment]
https://github.com/ubsuny/23-Homework3G1/blob/main/Algorithm.py
https://github.com/ubsuny/23-Homework3G1/blob/main/Period.py

These two are the previous algorithm.

**Comment by poojashresthacode** [comment]
https://github.com/ubsuny/23-Homework4G4/blob/main/periodic_test.py

This is the edited algorithm.

**Comment by pratibha77118** [comment]
Thank You @ Pooja.  @WildJimmy Yeah also I deleted the module of algorithm because initially the git hub action didn't work out. But I think it will work out now even if we use the algorithm with module too.

**Comment by poojashresthacode** [comment]
Hy @WildJimmy 

The changes in the algorithm were not the part of homework. I think there is no need to go into detail in the documentation part, But we got to know the important point while writing the workflow, which is the workflow doesn't work if we have to give the input manually through the terminal while running the algorithm. So, you can highlight this point as the main reason to change the algorithm and the rest is fine.

I hope it works.

**Comment by WildJimmy** [comment]
@poojashresthacode Under the tasks section of the homework, it does say that we should be including a changelog for the algorithm. Though I agree with your point that we shouldn't be going too in depth, I just gave a brief overview of what has been changed
