### ISSUE TITLE
Error while linting

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework4G4#40]
I get the following error while running the linting action. The linting process is completed successfully however the test failed because of this error. Any idea on how to resolve this issue??

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2.

**Comment by laserlab** [comment]
As I was writing in your related PR (link your PRs in issues!) #38 did you check if v4 of those workflows work?

**Comment by laserlab** [comment]
Why don’t you comment on the PR and request changes? @poojashresthacode

**Comment by poojashresthacode** [comment]
I should have done that. But, now she has done it already. Thanks for reminding me professor.

**Comment by pratibha77118** [comment]
@laserlab it was the issue I got by using version 2. I now changed it to version 4 and it works fine.
