### ISSUE TITLE
Are we supposed to use pytest or unittest to do the unit testing part of the HW?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework4G4#46]
Does it matter?

**Comment by reshnashrestha** [comment]
@AhmedCode99 unit test and pytest are totally different. 
unit test checks for your code running correctly or not while the pytest checks for some standard guidelines that codes need to follow in the unit test.

**Comment by poojashresthacode** [comment]
We must do pytest. And again we must do linting and get 10/10 rating for our code by editing it.
