### ISSUE TITLE
 How to create separate function / module for unit test?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G4#48]
Any ideas will be appreciated.

**Comment by poojashresthacode** [comment]
We have to create a separate test directory for this and create a test file there. You can check if it runs smoothly or not. I am doing it today. You can have a look after I do. or I can also send a merge request after doing it and you can make your own after having a look at it.

**Comment by reshnashrestha** [comment]
It appeared that I did this way earlier. I was just confused with the words. 
Can you please check out my work?
[projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)

**Comment by reshnashrestha** [comment]
Thank you for the suggestions @poojashresthacode
