### ISSUE TITLE
HW Realated

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G4#5]
Do you guys understand the question of the HW? It is not clear to me. If you understand, please let us know.

/

**Comment by reshnashrestha** [comment]
Yeah, @sharmistharanit it's kind of confusing. Any help will be appreciated.

**Comment by AhmedCode99** [comment]
You can learn more about developing GitHub Actions tasks in the GitHub Actions documentation: https://docs.github.com/en/actions

**Comment by poojashresthacode** [comment]
@Thankyou!
