### ISSUE TITLE
Unit test module, pytest and linting done.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework4G4#57]
Hi, @WildJimmy I have finished the work on the unit test. You can now view it in our repo to work on the documentation part.

**Comment by tirthbha** [comment]
@poojashresthacode I think you still have linting error to your unit test file, right?

**Comment by poojashresthacode** [comment]
Yaa, I tried and still working on it.

**Comment by reshnashrestha** [comment]
@tirthbha is the code rating of 10/10 necessary?

**Comment by tirthbha** [comment]
@reshnashrestha I think it not necessary but you can do as much as possible.

**Comment by WildJimmy** [comment]
Thanks for letting me know, it's included in the documentation so I feel I can close this issue
