### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework4G4#69]
Hi @WildJimmy,
I look through the documentation section and it seems like that are few things to be included. First we need to put the reference, indicate that the License allows the pervious code and also you can put changes in the change log too. @poojashresthacode gonna share what she has changed in her unit test. You too can put the output of pylint and pytest too. So I am hoping you will add these things and pull a final merge request.

**Comment by WildJimmy** [comment]
Yep, mentioned this in the related issue #70. Will work to include these before the deadline
