### ISSUE TITLE
Tasks Distribution

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework4G4#7]
Hi @WildJimmy & @poojashresthacode
Which project of earlier homework we gonna choose for this homework. It would be better if we decide it soon and start working on our project. Also we should allocate the task too.

**Comment by poojashresthacode** [comment]
Yeah, we can do any of yours. Is it okay ? @WildJimmy @pratibha77118

**Comment by WildJimmy** [comment]
Hi All,

If you'd like we can use my group's homework for the last assignment (https://github.com/ubsuny/23-Homework3G3), which calculates the spring constant of a given system. It's relatively simple so it should be nice to adapt with the github actions. Let me know if this works for you @pratibha77118 @poojashresthacode

**Comment by AhmedCode99** [comment]
multiple groups can use the same code

**Comment by poojashresthacode** [comment]
Sure!
