### ISSUE TITLE
No file named unittestcode.py in repository but you are linting unittestcode.py

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework4G4#76]
In unitlint.yml replace unittestcode.py with the actual Python file you want to lint. 

name: lint unittestcode.py
      run: pylint unittestcode.py #Replace with actual file name.

**Comment by WildJimmy** [comment]
This is an excellent point, will work to change this asap

**Comment by WildJimmy** [comment]
Just created the merge request that should fix this in https://github.com/ubsuny/23-Homework4G4/pull/78

**Comment by pratibha77118** [comment]
Also what does the changes do? It worked fine. Thanks for indicating @Pranjal-Srivastava-2023 .
