### ISSUE TITLE
Pushed Final Revisions to Documentation

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G4#79]
@pratibha77118 I just made the merge request for the suggested revisions to the documentation, as well as resolving an error in one of the linting actions. Please look it over and let me know if anything needs to be changed!

**Comment by pratibha77118** [comment]
@WildJimmy I was making some edits on documentation too with few references too. Its showing that I have to resolve the conflicts to merge your file. So I hope  things are included in documentation there.
