### ISSUE TITLE
Should We Rename Some Files?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G4#80]
I know it's a little late in the game, but should we rename some of our files? I didn't want to change anything too last minute if you're not all on board, but (for example) containing the unit test in final_code.py is a little confusing and nondescriptive when trying to find out which file does what. Please let me know what you think

**Comment by poojashresthacode** [comment]
Please don't change it now, otherwise, I will be confused about the filename when I present it. I hope you understand.
But, is it possible to change it after the presentation?

**Comment by WildJimmy** [comment]
Don't worry, I'll leave it the same now. If we do want to clean it up for posterity though I may change some files names later just to make the repository a little cleaner

**Comment by pratibha77118** [comment]
@WildJimmy we have to change the file name in .yml file too to make it work in git hub workflows if we change the filename of .py files in main repo.
