### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework4G4#9]
What is node.js and npm, do you guys have any idea about it? What technology stack are we working with?

**Comment by poojashresthacode** [comment]
Oh, node.js and npm is for jvascript. But how can we find out what technology stack are we working with? @laserlab. Professor, can you please explain briefly about it?

**Comment by laserlab** [comment]
I’m not sure what you mean with “technology stack”. We use python and C++ in this class.

**Comment by poojashresthacode** [comment]
I was asking AI about the GitHub action in unit testing. It gives some code like this and states "The code uses Node.js and npm, so adjust it if you're working with a different technology stack." I have attached the code below. And I am also searching whether Python or C++ is a technology stack. But, it says they aren't. 

It is what AI says, "No, Python is not a technology stack; it is a programming language. A technology stack typically refers to a combination of various software components, frameworks, and tools used to build and run a software application. Python, on the other hand, is a versatile and popular programming language that can be a part of a technology stack."

And I am not sure whether it is okay to get help from AI in these matters.

This is the code which I have mentioned above:

name: Unit Testing

on: [push] # Trigger the workflow on code pushes

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Adjust this to your project's Node.js version

    - name: Install dependencies
      run: npm install # Use the appropriate package manager (npm, yarn, etc.)

    - name: Run Unit Tests
      run: npm test # Adjust this to your testing command

**Comment by poojashresthacode** [comment]
@laserlab

**Comment by laserlab** [comment]
Now I get it, yes JavaScript would be the language in the above case. Technology stack would be for specific application.
